# Generated by Django 2.2.6 on 2022-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220531_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ANONYMOUS', 'anonymous'), ('USER', 'user'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], default='USER', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
