# Generated by Django 2.2.16 on 2022-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220606_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', through='reviews.Genre_Title', to='reviews.Genre'),
        ),
    ]
